LivroBook/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('book.urls')),
    path('social/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import IndexView, BookRegisterView, BookAllView, BookUpdateView

# {% url 'blog:post-list' %}
app_name = 'book'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('book-register', BookRegisterView.as_view(), name='book-register'),
    path('book-all', BookAllView.as_view(), name='book-all'),
    path('book-update/<int:pk>', BookUpdateView.as_view(), name='book-update'),
    # Default Django directory responsible for logging out the page and redirecting to the login page.
    path('logout/', auth_views.LogoutView.as_view(next_page='users:login'), name='logout'),
]

book/models.py
"""
-> BookRegisterModel: Database designated for the books that the user will register.
"""
from django.db import models
from users.models import User


class BookRegisterModel(models.Model):
    # "Models.OneToOneField" → User relationship: The UserConfirmModel model has a one-to-one relationship with user
    # model User using field user. This means that each User instance can have only one corresponding instance in
    # UserConfirmModel.
    # 'blank=True, null=True' → defines that the field accepts null values.
    # "title" → Book title.
    # "edition" → Book edition, can be null.
    # "npages" → number of book pages, can be null.
    # "begin" → initial day of reading, can be null.
    # "finish" → finishing day of reading, can be null.
    # "concluded" → if the book is finished, can be null.
    # "wish" → if the book is for wish list, can be null.
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField("Título", max_length=100)
    edition = models.CharField("Edição", max_length=50, blank=True, null=True)
    npages = models.IntegerField("Número de páginas", blank=True, null=True)
    begin = models.DateField("Início", blank=True, null=True)
    finish = models.DateField("Fim", blank=True, null=True)
    concluded = models.BooleanField("Terminado?", default=False, blank=True, null=True)
    wish = models.BooleanField("Desejo", default=False, blank=True, null=True)

    class Meta:
        # Customize how the model's singular name is displayed in the Django admin.
        verbose_name = "Book"
        # Customize how the model's plural name is displayed in the Django admin.
        verbose_name_plural = "Books"

book/forms.py
"""
-> BookRegisterForm: Formulário responsável por ativar o usuário a partir da chave enviada para ele por email.
"""
from django import forms
from .models import BookRegisterModel


class BookRegisterForm(forms.ModelForm):
    # Forms fields.
    title = forms.CharField(label="Título", max_length=100,
                            widget=forms.TextInput(attrs={'placeholder': 'Qual o nome do livro'}))
    edition = forms.CharField(label="Edição", max_length=50, required=False,
                              widget=forms.TextInput(attrs={'placeholder': 'Qual a edição do livro?'}))
    npages = forms.IntegerField(label="Número de páginas", required=False,
                                widget=forms.NumberInput(attrs={'placeholder': 'Quantas páginas tem o livro?'}))
    begin = forms.DateField(label="Início", required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    finish = forms.DateField(label="Término", required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    concluded = forms.BooleanField(label="Não terminou? Só cliclar na caixinha ao lado", required=False)
    wish = forms.BooleanField(label="É para lista de desejos?", required=False)

    def clean_concluded(self):
        if self.cleaned_data['concluded']:
            self.cleaned_data['concluded'] = False
        else:
            self.cleaned_data['concluded'] = True

        return self.cleaned_data['concluded']

    def clean_wish(self):
        if self.cleaned_data['wish']:
            self.cleaned_data['concluded'] = False

        return self.cleaned_data['wish']

    # Class to add additional metadata inside the form.
    class Meta:
        model = BookRegisterModel  # Template that will be used for the form.
        fields = ['title', 'edition', 'npages', 'concluded', 'begin', 'finish', 'wish']  # Forms view fields.
        ordering = ['id']

book/views.py
"""
-> @method_decorator(login_required, name='dispatch'): if the user is not registered, it redirects the page to the login.
-> IndexView: website index page. Displays data and tables regarding the books already registered by the user.
-> BookRegisteView: page to register new books.
-> BookAllView: page to present a table with all the books already registered and their information.
-> BookUpdateView: page to update a previously registered book.
"""
from datetime import date

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from django.views.generic import TemplateView, CreateView, UpdateView

from book.forms import BookRegisterForm
from users.decorators import login_required

from .models import BookRegisterModel


@method_decorator(login_required, name='dispatch')
class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        # Retrieve the logged-in user's email.
        pk = self.request.user.email

        # Create the data delivery variable.
        context = super().get_context_data(**kwargs)

        # Retrieves the first six values of the "BookRegisterModel" model based on the email.
        added = BookRegisterModel.objects.filter(user_id__email=pk).order_by('-id')[:6].values()

        for a in added:
            if a["concluded"] is False:
                a['concluded'] = "Não"
            else:
                a["concluded"] = "Sim"

            if a["wish"]:
                a['concluded'] = "Desejo"

            for key, value in a.items():
                if value is None or value == "":
                    a[key] = "-"

        # Create the 'added' list with the values retrieved from the database.
        context["added"] = added

        # Search all data that have 'wish' as true.
        context['wish'] = BookRegisterModel.objects.filter(user_id__email=pk, wish=True)
        # first six values of 'wish'.
        context['wish_table'] = context['wish'][:6].values()
        # Count how many 'wish' there are.
        context['wish_graphic'] = context['wish'].count()

        # Data related to books and pages read.
        context["nbook"], context["npages"], context["book"], context["pages"] = self.get_context_graphic()

        return context

    # Function to create the logic of division of books and pages read per month.
    # OBS: there Will only be books and pages that are completed.
    # OBS: the sum will be fully rolled back to the registration date of when the book was finished.
    def get_context_graphic(self):
        data = BookRegisterModel.objects.filter(user_id__email=self.request.user.email, concluded=True).values()
        dic_book = [{1: 0}, {2: 0}, {3: 0}, {4: 0}, {5: 0}, {6: 0},
                    {7: 0}, {8: 0}, {9: 0}, {10: 0}, {11: 0}, {12: 0}]
        dic_npages = [{1: 0}, {2: 0}, {3: 0}, {4: 0}, {5: 0}, {6: 0},
                      {7: 0}, {8: 0}, {9: 0}, {10: 0}, {11: 0}, {12: 0}]
        book = 0
        pages = 0

        for d in data:
            if d["finish"]:
                array = d["finish"].month - 1
                key = d["finish"].month
                book += 1
                dic_book[array][key] += 1
                if d["npages"]:
                    dic_npages[array][key] += d["npages"]
                    pages += d["npages"]

        return dic_book, dic_npages, book, pages


@method_decorator(login_required, name='dispatch')
class BookRegisterView(CreateView):
    model = BookRegisterModel
    form_class = BookRegisterForm
    template_name = "book-register.html"
    success_url = reverse_lazy('book:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        cleaned_data = form.cleaned_data

        # Check if the start date is greater than the end date, if true, return the error.
        try:
            if cleaned_data["begin"] > cleaned_data["finish"]:
                form.add_error('finish', 'Data de início deve ser menor que data final')
                return self.form_invalid(form)

            elif cleaned_data["finish"] > date.today():
                form.add_error('finish', 'Data de término deve ser menor que a data de hoje')
                return self.form_invalid(form)

        except TypeError:
            pass

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class BookAllView(TemplateView):
    template_name = "book-all.html"

    def get_context_data(self, **kwargs):
        pk = self.request.user.email

        context = super().get_context_data(**kwargs)  # Cria a variável de entrega de dados.
        # Recupera os seis primeiros valores do modelo "BookRegisterModel" baseado no email.
        data = BookRegisterModel.objects.filter(user_id__email=pk).values()
        for d in data:
            if d["concluded"] is False:
                d['concluded'] = "Não"
            else:
                d["concluded"] = "Sim"

            if d["wish"]:
                d['wish'] = "Sim"
                d['concluded'] = "Não"
            else:
                d['wish'] = "Não"

            for key, value in d.items():
                if value is None or value == "":
                    d[key] = "-"

        context["data"] = data  # Cria a lista 'added' que com os valores recuperados do banco.

        return context


class BookUpdateView(UpdateView):
    model = BookRegisterModel
    template_name = 'book-update.html'
    form_class = BookRegisterForm

    def get_context_data(self, **kwargs):
        # Retrieve the logged-in user's email.
        pk = self.kwargs['pk']
        context = super().get_context_data(**kwargs)
        context["title"] = BookRegisterModel.objects.get(pk=pk).title

        return context

    def post(self, request, *args, **kwargs):
        if 'delete' in request.POST:
            return self.delete(request, *args, **kwargs)
        else:
            return super().post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.delete()
        return HttpResponseRedirect(self.get_success_url())

    def form_valid(self, form):
        form.instance.user = self.request.user
        cleaned_data = form.cleaned_data

        try:
            if cleaned_data["begin"] > cleaned_data["finish"]:
                form.add_error('finish', 'Data de início deve ser menor que data final')
                return self.form_invalid(form)

            elif cleaned_data["finish"] > date.today():
                form.add_error('finish', 'Data de término deve ser menor que a data de hoje')
                return self.form_invalid(form)

        except TypeError:
            pass

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('book:index')

book/templates/book-all.html
{% extends 'navbar.html' %}statistics
{% load static %}
{% block content %}
<main id="bookAll">
    <section class="table">
        <div>
            <p class="title text-center mbotton20">Livros cadastrados</p>
            <span class="alert">* Para editar algum, basta clicar no nome do livro.</span>
            <table>
                <tr>
                    <th>Nome</th>
                    <th>Editora</th>
                    <th>Páginas</th>
                    <th>Início</th>
                    <th>Fim</th>
                    <th>Terminado?</th>
                    <th>Lista de Desejos</th>
                </tr>
                {% for d in data %}
                <tr>
                    <td><a class="black bold" href="{% url 'book:book-update' d.id %}">{{ d.title }}</a></td>
                    <td>{{ d.edition }}</td>
                    <td>{{ d.npages }}</td>
                    <td>{{ d.begin|date:"d/m/Y" }}</td>
                    <td>{{ d.finish|date:"d/m/Y" }}</td>
                    <td>{{ d.concluded }}</td>
                    <td>{{ d.wish }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </section>
</main>
{% endblock %}

book/templates/book-register.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<main id="registerBook">
    <section class="left">

        <span class="bold text-center title">Vamos cadastrar um livro</span>
        <form action="#" method="POST">
            {% csrf_token %}
            <label for="id_title">{{ form.title.label }}*</label>
            {{ form.title }}
            <label for="id_edition">{{ form.edition.label }}</label>
            {{ form.edition }}
            <label for="id_npages">{{ form.npages.label }}</label>
            {{ form.npages }}
            <div class="middle">
                <div>
                    <label for="id_begin">{{ form.begin.label }}</label>
                    {{ form.begin }}
                </div>
                <div>
                    <label for="id_finish">{{ form.finish.label }}</label>
                    {{ form.finish }}
                </div>
            </div>
            <div class="checkboxmiddle">
                <label for="id_concluded">{{ form.concluded.label }}</label>
                {{ form.concluded }}
            </div>
            <div class="checkboxmiddle">
                <label for="id_wish">{{ form.wish.label }}</label>
                {{ form.wish }}
            </div>
            <div class="buttonsMiddle">
                <button type="submit">CADASTRAR</button>
                <a href="{% url 'book:index' %}"><button>VOLTAR</button></a>
            </div>
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <p class="alert bold">{{ error }} </p>
            {% endfor %}
            {% endfor %}
            {% endif %}
            <br>
            <p class="small">* Campos obrigatórios</p>
        </form>
    </section>

    <section class="right"><img src="{% static 'icons/remove.svg' %}" alt=""></section>
</main>
{% endblock %}

book/templates/book-update.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<main id="registerBook">
    <section class="left">
        <span class="bold text-center title">{{ title.title }} </span>
        <form method="POST">
            {% csrf_token %}
            <label for="id_title">{{ form.title.label }}*</label>
            {{ form.title }}
            <label for="id_edition">{{ form.edition.label }}</label>
            {{ form.edition }}
            <label for="id_npages">{{ form.npages.label }}</label>
            {{ form.npages }}
            <div class="middle">
                <div>
                    <label for="id_begin">{{ form.begin.label }}</label>
                    {{ form.begin }}
                </div>
                <div>
                    <label for="id_finish">{{ form.finish.label }}</label>
                    {{ form.finish }}
                </div>
            </div>
            <div class="checkboxmiddle">
                <label for="id_concluded">{{ form.concluded.label }}</label>
                {{ form.concluded }}
            </div>
            <div class="checkboxmiddle">
                <label for="id_wish">{{ form.wish.label }}</label>
                {{ form.wish }}
            </div>
            <div class="buttonsMiddle">
                <button type="submit">ATUALIZAR</button>
                <button type="submit" name="delete" onclick="deleteFieldRequired()">EXCLUIR</button>
            </div>
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <p class="alert bold">{{ error }} </p>
            {% endfor %}
            {% endfor %}
            {% endif %}
            <br>
            <p class="small">* Campos obrigatórios</p>
        </form>
    </section>

    <section class="right"><img src="{% static 'icons/remove.svg' %}" alt=""></section>
</main>


{% endblock %}

book/templates/index.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<main class="homeData">
    <section class="table mbotton20">
        <div>
            <p class="title text-center mbotton20">Últimos Adicionados</p>
            <table id="firstTable">
                <tr>
                    <th>Nome</th>
                    <th>Páginas</th>
                    <th>Início</th>
                    <th>Fim</th>
                    <th>Terminado?</th>
                </tr>
                {% for a in added %}
                <tr>
                    <td>{{ a.title }}</td>
                    <td>{{ a.npages }}</td>
                    <td>{{ a.begin|date:"d/m/Y" }}</td>
                    <td>{{ a.finish|date:"d/m/Y" }}</td>
                    <td>{{ a.concluded }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="mbotton20">
            <p class="title text-center mbotton20">Lista de desejos</p>
            <table id="secondTable">
                <tr>
                    <th>Nome</th>
                </tr>
                {% for w in wish_table %}
                <tr>
                    <td>{{ w.title }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </section>

    <section class="statistics mbotton20">
        <div class="nBooks">
            <p class="title bold mbotton20">Livros lidos</p>
            <p class="bold text-center purple">{{ book }}</p>
        </div>

        <div class="nPages">
            <p class="title bold mbotton20">Páginas lidas</p>
            <p class="bold text-center purple">{{ pages }}</p>
        </div>

        <div class="wishBooks">
            <p class="title bold mbotton20">Desejados</p>
            <p class="bold text-center purple">{{ wish_graphic }}</p>
        </div>
    </section>

    <section class="graphics">
        <div class="background">
            <p class="title bold">Livros lidos por mês</p>
            <canvas id="nBooks"></canvas>
        </div>
        <div class="background">
            <p class="title bold">Páginas lidos por mês</p>
            <canvas id="nPages"></canvas>
        </div>
    </section>
    {% for f in finish %}
    {{ f }}
    {% endfor %}
</main>
<script>

    const nBooksData = []
    {% for item in nbook %}
    {% for key, value in item.items %}
    nBooksData.push({{ value }})
    {% endfor %}
    {% endfor %}

    const nPagesData = []
    {% for item in npages %}
    {% for key, value in item.items %}
    nPagesData.push({{ value }})
    {% endfor %}
    {% endfor %}

</script>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/canvas.js' %}"></script>
{% endblock %}

book/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <!--CSS-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--Javascript-->
    <script src="{% static 'js/script.js' %}"></script>
    <!--FontAwesome-->
    <script src="https://kit.fontawesome.com/82f797382f.js" crossorigin="anonymous"></script>
</head>

<body>
    <nav>
        <div class="logo_header">
            <a href="{% url 'book:index' %}" class="logo">
                <h1 class="bold text-center">LivroBook</h1>
            </a>
            <button class="navbar_toggle">
                <i class="fas fa-bars"></i>
            </button>
        </div>

        <ul class="main_nav">
            <li>
                <a href="{% url 'book:index' %}" class="nav_links">HOME</a>
            </li>
            <li>
                <a href="{% url 'book:book-register' %}" class="nav_links">REGISTRAR</a>
            </li>
            <li>
                <a href="{% url 'book:book-all' %}" class="nav_links">TODOS</a>
            </li>
            <li>
                <a href="{% url 'book:logout' %}" class="nav_links">SAIR</a>
            </li>
        </ul>
    </nav>

    {% block content %}
    {% endblock %}
    <footer>
        <h1>RODAPÉ</h1>
    </footer>

    <!--Javascript-->
    <script src="{% static 'js/endscript.js' %}"></script>
</body>

</html>