LivroBook/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('book.urls')),
    path('social/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import IndexView, BookRegisterView, BookAllView, BookUpdateView

# {% url 'blog:post-list' %}
app_name = 'book'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('book-register', BookRegisterView.as_view(), name='book-register'),
    path('book-all', BookAllView.as_view(), name='book-all'),
    path('book-update/<int:pk>', BookUpdateView.as_view(), name='book-update'),
    # Default Django directory responsible for logging out the page and redirecting to the login page.
    path('logout/', auth_views.LogoutView.as_view(next_page='users:login'), name='logout'),
]

users/urls.py
from django.urls import path

from .views import LoginView, UserRegisterView, UserConfirmView, PasswordResetView, CustomPasswordResetConfirmView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('register', UserRegisterView.as_view(), name="register"),
    path('confirm/<int:pk>', UserConfirmView.as_view(), name='confirm'),
    path('password-reset', PasswordResetView.as_view(), name="password_reset"),
    path('password-reset/confirm/<str:uidb64>/<str:token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm')
]

users/models.py
"""
# -> UserManager: handle creating and managing users.
# -> User: defines a custom user template with additional fields, authentication settings, and methods
# custom.
# -> UserConfirmModel: confirmation key for a user
"""
from django.db import models

from django.contrib.auth.models import AbstractUser, BaseUserManager


# The BaseUserManager is used to customize user creation logic, such as using a field email instead of a username field
# for authentication, add custom fields to user template, define additional restrictions during user creation, among
# other customizations.
class UserManager(BaseUserManager):
    # Normalize the email address by lowercase the domain part of it.
    def normalize_email(self, email):
        email = email or ""
        try:
            email_name, domain_part = email.strip().rsplit('@', 1)
        except ValueError:
            raise ValueError('O email não possui o padrão correto: email@dominio.com')
        else:
            email = email_name.lower() + "@" + domain_part.lower()
        return email

    # The _create_user function is an internal BaseUserManager method used to create a user.
    def _create_user(self, email, password, **extra_fields):
        # Check if the email was provided.
        if not email:
            raise ValueError("O email é obrigatório")

        # Check if the password was provided.
        if not password:
            raise ValueError("Senha obrigatória")

        # Match the email typed by the user to the right email pattern.
        email = self.normalize_email(email)
        # Defining email as the login method for the user.
        user = self.model(email=email, **extra_fields)
        # Set and encrypt the password.
        user.set_password(password)
        # Save the customer user model.
        user.save(using=self._db)

        return user

    # The function create_user is a public method of BaseUserManager that uses the internal method _create_user
    # to create a user with some default values.
    def create_user(self, email, password=None, **extra_fields):
        # Defines that the user is not a staff member.
        extra_fields.setdefault('is_staff', False)
        # Defines that the user is not a superuser member.
        extra_fields.setdefault('is_superuser', False)
        # Defines that the user is not an active member at the time of account creation.
        extra_fields.setdefault('is_active', False)

        return self._create_user(email, password, **extra_fields)

    # The function create_superuser is a public method of BaseUserManager that uses the internal method _create_user
    # to create a superuser with some default values.
    def create_superuser(self, email, password, **extra_fields):
        # Defines that the superuser is a staff member.
        extra_fields.setdefault('is_staff', True)
        # Defines that the superuser is a superuser member.
        extra_fields.setdefault('is_superuser', True)
        # Defines that the superuser is an active member.
        extra_fields.setdefault('is_active', True)

        return self._create_user(email, password, **extra_fields)

    class Meta:
        use_in_migrations = True


class User(AbstractUser):
    # User-supplied information for additional fields
    # "email" → user email.
    # "first_name" → user-first name.
    # "last_name" → user-last name.
    email = models.EmailField('E-mail', max_length=200, unique=True)
    first_name = models.CharField("Primeiro nome", max_length=20)
    last_name = models.CharField("Sobrenome", max_length=50)

    # Automatic information saved in the bank.
    # "date_joined" → date and time of user registration set to 'now' by Django.
    date_joined = models.DateTimeField('Data de cadastro', auto_now_add=True)

    # User Model information.
    # USERNAME_FIELD → 'email' field is used as the unique identification field for authentication.
    # REQUIRED_FIELD → which additional fields are required when creating a user.
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    # This function returns the absolute URL for a specific user, based on their pk (primary key).
    def get_absolute_url(self):
        return f'/confirm/{self.pk}'

    # This function returns a string representation of the User object and the user's email.
    def __str__(self):
        return self.email

    # Responsible for managing user creation, including methods like create_user and create_superuser.
    objects = UserManager()


class UserConfirmModel(models.Model):
    # "Models.OneToOneField" → User Relationship: The UserConfirmModel model has a one-to-one relationship with user
    # model User using field user. This means that each User instance can have only one corresponding instance in
    # UserConfirmModel.

    # User-supplied information for additional fields
    # "user" → user email.
    # "key" → User confirmation key.
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user')
    key = models.CharField("key", max_length=6)

    # Automatic information saved in the bank.
    # "created" → automatically sets the date and time the field was created.
    created = models.DateTimeField('Data de cadastro', auto_now_add=True)

    class Meta:
        verbose_name = "Confirm User Key"
        verbose_name_plural = verbose_name

users/views.py
"""
-> LoginView: based on FormView responsible for generating the user's Login page if he is not yet logged in or opening
the home page if he is logged in.
-> UserRegisterView: based on CreateView responsible for generating a user registration page.
-> ConfirmUserView: based on UpdateView responsible for generating the registration confirmation page.
-> PasswordResetView: based on TemplateView responsible for generating the link submission page password recovery.
-> CustomPasswordResetConfirmView: based on PasswordResetConfirmView responsible for generating the password reset
page password.
"""
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetConfirmView
from django.shortcuts import redirect
from django.urls import reverse_lazy

from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.utils.http import urlsafe_base64_encode

from django.views.generic import CreateView, FormView, UpdateView

from LivroBook import settings
from .models import User, UserConfirmModel
from .forms import UserRegisterForm, UserConfirmForm, PasswordResetForm, CustomPasswordResetConfirmForm

import string
import random


# Function to create the user confirmation key randomly with numbers and letters with size 6.
def random_key_value():
    # Defines a string containing all uppercase letters and digits.
    chars = string.ascii_uppercase + string.digits

    # Defines the number of characters that will have the random value.
    size = 6

    # Combines all generated characters into a single string, forming the 6-character random key.
    return ''.join(random.choice(chars) for _ in range(size))


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'login.html'
    success_url = reverse_lazy('book:index')

    # It is used to determine which templates should be used to render the view.
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('book:index')
        return super().get(request, *args, **kwargs)

    # The form_valid() method is a standard Django method for when the submitted form is valid.
    def form_valid(self, form):
        # Retrieve form input "email".
        username = form.cleaned_data['username']
        # Retrieve "password" from form input
        password = form.cleaned_data['password']
        # Store the recovered data.
        user = authenticate(self.request, username=username, password=password)

        # If user differs from None, that is, the credentials are valid, the user is authenticated by calling the
        # login() function, passing the request and the user object.
        # If the credentials are invalid, the form.add_error() function is used to add an error to the form.
        if user is not None:
            # Persist a user ID on the backend of the request.
            login(self.request, user)
        else:
            form.add_error(None, 'Credenciais inválidas')
            return self.form_invalid(form)

        return super().form_valid(form)

    def form_invalid(self, form):
        # Get the "username" filled in the form.
        username = form.cleaned_data['username']
        # Get the "password" filled in the form.
        password = form.cleaned_data['password']

        # Try - Except responsible for checking if the user exists in the database, if it exists, the problem is in the
        # wrong password, if it does not exist, the login problem is in the user's existence.
        try:
            # Locate the user by the username passed in the form.
            user = User.objects.get(username=username)

            # Only the password is incorrect.
            if not user.check_password(password):
                form.add_error('password', 'A senha está incorreta.')
                return self.render_to_response(self.get_context_data(form=form))

        # User isn't found in the User database.
        except User.DoesNotExist:
            form.add_error('username', 'Usuário não encontrado.')
            return self.render_to_response(self.get_context_data(form=form))

        return super().form_invalid(form)


class UserRegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'register.html'

    # It is used to determine which templates should be used to render the view.
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('book:index')
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        # Save data in the Create User model.
        create_user = form.save()

        # Create instance for the Confirm User model.
        confirm_user = UserConfirmModel()
        confirm_user.key = random_key_value()
        # Relate the model
        confirm_user.user = create_user

        # Save model 2
        confirm_user.save()

        form.send_mail()

        return super().form_valid(form)

    # The get_success_url() method is used to determine the redirect URL after successful form submission.
    # Will send to 'confirm' page based on current user pk.
    def get_success_url(self):
        return self.object.get_absolute_url()


class UserConfirmView(UpdateView):
    model = User
    form_class = UserConfirmForm
    template_name = 'confirm.html'
    success_url = reverse_lazy('book:index')

    def form_valid(self, form):
        key = form.cleaned_data['key']
        try:
            UserConfirmModel.objects.get(key=key)
        except UserConfirmModel.DoesNotExist:
            form.add_error('key', 'A chave não é igual à enviada por e-mail. Favor verificar novamente.')
            return super().form_invalid(form)

        response = super().form_valid(form)
        # Get the user object currently being edited using the method.
        user = self.get_object()
        # Set the user's is_active attribute to True.
        user.is_active = True
        # Save the user with the changes made.
        user.save()

        return response


class PasswordResetView(FormView):
    template_name = "password_reset.html"
    form_class = PasswordResetForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form, *args, **kwargs):
        # Retrieve form input "email".
        email = form.cleaned_data['email']

        try:
            user = User.objects.get(email=email)
            # Base64 encode the primary key and create the UUID64.
            uidb64 = urlsafe_base64_encode(str(user.pk).encode('utf-8'))
            # Create the user token.
            token = default_token_generator.make_token(user)

            # Creation of the password recovery link.
            reset_url = f"{settings.BASE_URL}/password-reset/confirm/{uidb64}/{token}/"

            form.send_mail(reset_url)

            return super().form_valid(form)
        except User.DoesNotExist:
            form.add_error('email', 'Usuário não encontrado')

            return self.form_invalid(form)


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'password-reset-confirm.html'
    form_class = CustomPasswordResetConfirmForm
    success_url = reverse_lazy('users:login')

users/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="cache-control" content="max-age=0" />
  <meta http-equiv="cache-control" content="no-cache" />
  <meta http-equiv="expires" content="0" />
  <!--CSS-->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!--Javascript-->
  <script src="{% static 'js/script.js' %}"></script>
  <!--FontAwesome-->
  <script src="https://kit.fontawesome.com/82f797382f.js" crossorigin="anonymous"></script>
</head>

<body>
  {% block content %}
  {% endblock %}
  <!--Javascript-->
  <script src="{% static 'js/endscript.js' %}"></script>
</body>

</html>

users/templates/confirm.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main id="gridConfirm">
    <p class="bold confirmTitle">Confirme seu registro</p>
    <p class="small bold">O código de 6 dígitos foi enviado para seu email</p>
    <form action="#" method="POST" autocomplete="off" class="divCenter">

        {% csrf_token %}
        {{ form.key }}
        {% if form.errors %}
        <p class="alert bold">Sua chave não corresponde à enviada por E-mail.</p>
        <p class="alert bold">Favor tentar novamente</p>
        {% endif %}
        <div>
            <button type="submit">CONFIRMAR</button>
        </div>
    </form>
</main>
{% endblock %}

users/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main id="loginSection">

    <section class="left">
        <h1 class="bold">LivroBook</h1>
        <div class="form">
            <p class="bold">Seja bem vindo de novo</p>
            <form action="#" method="POST">
                {% csrf_token %}
                <label class="bold">{{ form.username.label }}</label>
                {{ form.username }}

                <label class="bold">{{ form.password.label }}</label>
                {{ form.password }}
                <div class="divCenter">
                    <button type="submit">ENTRAR</button>
                </div>
            </form>
        </div>
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <p class="alert bold">{{ error }} </p>
        {% endfor %}
        {% endfor %}
        {% endif %}
        <p class="bold">- OR -</p>
        <div class="loginIcon">
            <a href="{% url 'social:begin' 'facebook' %}"><img src="{% static 'icons/facebook.svg' %}" alt="facebook-icon"></a>
            <a href="{% url 'social:begin' 'google-oauth2' %}"><img src="{% static 'icons/google.svg' %}" alt="google-icon"></a>
            <a href="{% url 'social:begin' 'instagram' %}"><img src="{% static 'icons/instagram.svg' %}" alt="instagram-icon"></a>
        </div>
        <div class="text">
            <p class="registre">Não possui conta? <a href="{% url 'users:register' %}" class="bold">Registre-se!</a></p>
            <p>Esqueceu a senha? <a href="{% url 'users:password_reset' %}" class="bold">Recupere-a!</a></p>
        </div>
    </section>
    <section class="right">
        <img src="../img/icon_index.svg" alt="">
    </section>
</main>
{% endblock %}

users/templates/password-reset-confirm.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main id="gridPassword">
    <section>
        <p class="bold title mbotton20">Está com problemas para acessar sua conta?</p>
        <p class="mbotton20 bold">Estamos quase lá. Agora só falta colocar sua senha nova e estará pronto.</p>
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            {{ form.new_password1 }}
            {{ form.new_password2 }}
            <div>
                <button type="submit">CONFIRMAR</button>
            </div>
        </form>
    </section>
</main>
{% endblock %}

users/templates/password_reset.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main id="gridPassword">
    <section>
        <p class="bold title mbotton20">Está com problemas para acessar sua conta?</p>
        <p>Favor informe seu e-mail de cadastro.</p>
        <p class="mbotton20">Iremos te encaminhar o link com a recuperação de senha.</p>
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            {{ form.email }}
            <div>
                <button type="submit">CONFIRMAR</button>
            </div>
        </form>
        <p class="bold mbotton20">- OR -</p>
        <a class="bold" href="#">Criar nova conta</a>
    </section>
</main>
{% endblock %}

users/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main id="gridRegister">
    <section class="left">

        <p class="bold title">Criar conta</p>
        <form action="{% url 'users:register' %}" method="POST">
            {% csrf_token %}
            <label for="id_email" class="bold">{{ form.email.label }}</label>
            {{ form.email }}
            <label for="id_first_name" class="bold">{{ form.first_name.label }}</label>
            {{ form.first_name }}
            <label for="id_last_name" class="bold">{{ form.last_name.label }}</label>
            {{ form.last_name }}
            <label for="id_password1" class="bold">{{ form.password1.label }}</label>
            {{ form.password1 }}
            <label for="id_password2" class="bold">{{ form.password2.label }}</label>
            {{ form.password2 }}
            <div class="buttonCenter">
                <button type="submit" class="bold">CADASTRAR</button>
            </div>
            {% for field in form %}
            {% for error in field.errors %}
            <p class="alert bold">{{ error }} </p>
            <p class="alert bold">{{ error.label }} </p>
            {% endfor %}
            {% endfor %}
        </form>

    </section>
    <section class="right">
        <img src="{% static 'img/maquina_escrever.png' %}" alt="maquina-de-escrever">
    </section>
</main>
{% endblock %}